version: '3.8'

services:
  app:
    tty: true
    stdin_open: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    depends_on:     
      - database
    networks:
      - app-network

  database:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  # necessario caso queira testar o recebimento de emails
  # mailcatcher:
  #   image: schickling/mailcatcher
  #   ports:
  #     - "1025:1025"
  #     - "1080:1080"
  #   networks:
  #     - app-network

networks:
  app-network:
volumes:
  gem_cache:
  db_data:
  node_modules:
